<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <!-- NOTE: joint must match the name of the module -->
  <xacro:macro name="paddle_end" params="name child extension paddle_mass paddle_diameter">
    <xacro:property name="tube_mass" value="${0.4 * (extension + 0.03) + 0.26}"/>
    <xacro:property name="edge_to_center" value="${.02}"/>
    <xacro:property name="paddle_height" value="${.025}"/>

    <link name="${name}/INPUT_INTERFACE">

      <visual>
        <origin xyz="0 0 ${(extension-paddle_height)/2}" rpy="0 0 0" />

        <geometry>
          <cylinder length="${extension-paddle_height}" radius=".016" />
        </geometry>

        <material name="orange">
          <color rgba="${255/255} ${108/255} ${10/255} 1.0"/>
        </material>
      </visual>

      <visual>
        <origin xyz="0 0 ${extension-(paddle_height/2)}" rpy="0 0 0" />
        <geometry>
          <cylinder length="${paddle_height}" radius="${paddle_diameter/2}"/>
        </geometry>
        <material name="orange">
          <color rgba="${255/255} ${108/255} ${10/255} 1.0"/>
        </material>
      </visual>

      <collision>
        <origin xyz="0 0 ${(extension-paddle_height)/2}" rpy="0 0 0" />
        <geometry>
          <cylinder length="${extension-paddle_height}" radius=".016" />
        </geometry>
      </collision>

      <collision>
        <origin xyz="0 0 ${extension-(paddle_height/2)}" rpy="0 0 0" />
        <geometry>
          <cylinder length="${paddle_height}" radius="${paddle_diameter/2}" />
        </geometry>
      </collision>


      <!-- Approximate inertia as thin rod about x axis -->
      <inertial>
        <origin xyz="0 0 ${(extension-paddle_height)/2}" rpy="0 0 0" />
        <mass value="${tube_mass}"/>
        <inertia  ixx="0.0" ixy="0.0"  ixz="0.0"  iyy="${tube_mass * extension * extension / 12.0}"  iyz="0.0"  izz="${tube_mass * extension * extension / 12.0}"/>
      </inertial>

      <inertial>
        <origin xyz="0 0 ${extension-(paddle_height/2)}" rpy="0 0 0" />
        <mass value="${paddle_mass}"/>
        <inertia  ixx="0.0" ixy="0.0"  ixz="0.0"  iyy="${paddle_mass * paddle_height * paddle_height / 12.0}"  iyz="0.0"  izz="${paddle_mass * paddle_height * paddle_height / 12.0}"/>
      </inertial>


    </link>
    <joint name="${name}/OUTPUT_JOINT" type="fixed">
      <parent link="${name}/INPUT_INTERFACE"/>
      <child link="${child}/INPUT_INTERFACE"/>
      <origin xyz="0 0 ${extension}" rpy="0 0 0"/>
    </joint>
    <gazebo reference="${name}/INPUT_INTERFACE">
      <selfCollide>true</selfCollide>
    </gazebo>
  </xacro:macro>
</robot>

